project:
  type: website
  output-dir: docs
  resources: 
    - files/cv.pdf

website:
  page-navigation: true
  title: "Alex Trinidad"
  favicon: logo.png
  cookie-consent: false
  page-footer:
    left: "&copy; Copyright 2025 Alexander Trinidad. Licensed under [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"
    right: "Built with ![](images/fa6-brands--r-project.svg) and 
    [Quarto](https://quarto.org/). See code inspired by these [sources](source.qmd)"

  navbar:
    background: secondary
    search: true
    pinned: true
    left:
      - href: index.qmd
        text: Home
        
      - href: about.qmd
        text: About
        
      - href: publications.qmd
        text: Publications

    right:
      - text: "![](images/ri--bluesky-fill.svg)"
        href: https://bsky.app/profile/alextrinidad.bsky.social
      - text: "![](images/mdi--linkedin.svg)"
        href: https://www.linkedin.com/in/alexander-trinidad-pascual/
      - text: "![](images/pajamas--github.svg)"
        href: https://github.com/alexandertrinidad
      - text: "![](images/simple-icons--osf.svg)"
        href: https://osf.io/mdre4/
      - text: "![](images/simple-icons--orcid.svg)"
        href: https://orcid.org/0000-0002-0762-5367
      - text: "![](images/academicons--google-scholar.svg)"
        href: https://scholar.google.com/citations?user=JZ1gq6AAAAAJ&hl=en&oi=ao
      - text: "![](images/academicons--cv.svg)"
        href: files/cv.pdf

   
        
    # right:
    #   - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
    #     href: https://bsky.app/profile/alextrinidad.bsky.social
    #     rel: me
    #     
    #   - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
    #     href: https://github.com/alexandertrinidad
    #     rel: me
    #     
    #   - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
    #     href: https://www.linkedin.com/in/alexander-trinidad-pascual/
    #     rel: me
    #     

format:
  html:
    theme: 
      - html/ath.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai

  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true



