---
title: "Comparing Safety Perceptions and Active Mobility in Two Urban Settings: A Case Study"
type: "article"
author: 
  - name: Laura Vozmediano
    url: https://www.ehu.eus/en/web/dms/laura-vozmediano-sanz
    orcid: 0000-0003-3239-8327
    affiliation: University of the Basque Country, Spain
  - name: Mikel Subiza-Pérez
    orcid: 000-0002-6843-8557
    affiliation: University of the Basque Country, Spain
  - name: César San Juan
    url: https://www.ehu.eus/en/web/dms/director 
    orcid: 0000-0001-8067-6729
    affiliation: University of the Basque Country, Spain
  - name: Alex Trinidad
    url: https://www.alexandertrinidad.com 
    orcid: 0000-0002-0762-5367
    affiliation:  University of Cologne, Germany

year: "2025"
publication: "Security Journal"
materials: "https://osf.io/4j5t9/"
preprint: "https://doi.org/10.31219/osf.io/m2zyc"
toc: false
categories:
  - crime perceptions
  - active mobility
  - CPTED
---

## Citation (APA 7)

> Vozmediano, L., Subiza-Pérez, M., San Juan, C., & Trinidad, A. (Accepted). Comparing Safety Perceptions and Active Mobility in Two Urban Settings: A Case Study. *Security Journal*


## Abstract
Perceived (un)safety significantly impacts urban quality of life, shaping mobility dynamics and public space use. This study examines differences in safety perceptions across two environments and analyzes variables influencing active transportation decisions (walking or cycling) within these contexts. Using surveys and systematic observation in neighborhoods of differing socio-economic levels, we also explore the relationship between built environment design, walkability, and safety. Residents in disadvantaged neighborhoods reported higher unsafety levels and greater disruption in mobility dynamics, with safety concerns playing a more prominent role in their decisions. These findings help clarify inconsistencies in literature regarding perceived unsafety and active mobility.