---
title: "Trends in Public Crime Concerns in Germany: A Bounding Analysis of Periodic Change"
type: "working-papers"
author:  
  - name: Gordey Yastrebov
    url: https://iss-wiso.uni-koeln.de/de/institut/personen-a-z/y/dr-gordey-yastrebov
    orcid: 0000-0002-6100-4270
    affiliation: University of Cologne, Germany
  - name: Alex Trinidad
    url: https://www.alexandertrinidad.com 
    orcid: 0000-0002-0762-5367
    affiliation:  University of Cologne, Germany
  - name: Thomas Leopold
    url: https://www.thomasleopold.eu/
    orcid: 0000-0001-5554-3254
    affiliation: University of Cologne, Germany
year: "2024"
publication: "SocArXiv"
doi: "https://doi.org/10.31235/osf.io/7t8ds"
preprint: "https://osf.io/preprints/socarxiv/7t8ds_v1"
toc: false
categories:
  - APC Analysis
  - crime perceptions
  - working paper
---

## Citation (APA 7)

> Yastrebov, G., Trinidad, A., & Leopold, T. (2024). Trends in Public Crime Concerns in Germany: A Bounding Analysis of Periodic Change. *SocArXiv*.


## Abstract
In this paper, we ask whether broader societal changes in Germany over the last three decades have been accompanied by a secular rise or decline in public concerns about crime. We conceptualize the aggregate effect of these changes as a period effect to be identified in a framework of age-period-cohort (APC) analysis. Upon evaluation of previous research, we argue that the secular trend is challenging to identify directly both for empirical and theoretical reasons. However, using Fosse and Winship’s bounding approach to APC analysis, we show that the challenge can be resolved indirectly, and identify a declining period trend under an intuitive and theoretically warranted assumption that crime concerns are unlikely to decrease from late adolescence into adulthood.